version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - redisHost=redis
      - redisPort=6379
      - pgUser=your_username
      - pgHost=postgres
      - pgDatabase=your_database_name
      - pgPassword=your_password
      - pgPort=5432
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - worker
      - postgres

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
